language:
  ruby

rvm:
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'
  - '2.5.0'

script:
  - bundle exec rubocop
  - bundle exec rspec
  - rake install
  # - tvseries bb


install:
  - gem install bundler
  - bundle install
